{{- if not .Values.twilio.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubewa-operator.fullname" . }}-twilio-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubewa-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  accountSID: {{ .Values.twilio.accountSID | quote }}
  authToken: {{ .Values.twilio.authToken | quote }}
  fromNumber: {{ .Values.twilio.fromNumber | quote }}
{{- end }}
